# Generated by Django 5.1.4 on 2025-04-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeuser",
            name="experience",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.experience",
                verbose_name="",
            ),
        ),
    ]
