# Generated by Django 5.1.4 on 2025-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_experience_end_date_month_experience_end_date_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillcategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
            },
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date_month",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date_year",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
