# Generated by Django 5.1.4 on 2025-05-01 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_resumeuser_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "experience",
                    models.ManyToManyField(blank=True, to="portfolio.experience"),
                ),
                (
                    "languages",
                    models.ManyToManyField(blank=True, to="portfolio.languages"),
                ),
                (
                    "libraries",
                    models.ManyToManyField(blank=True, to="portfolio.libraries"),
                ),
                ("project", models.ManyToManyField(blank=True, to="portfolio.project")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ResumeUser",
        ),
    ]
