# Generated by Django 5.1.4 on 2025-05-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolio_delete_resumeuser"),
    ]

    operations = []
