# Generated by Django 5.1.4 on 2025-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_skillcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
