# Generated by Django 5.1.4 on 2025-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_experience_end_date_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
