# Generated by Django 5.1.4 on 2025-05-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_auto_20250501_0807"),
    ]

    operations = []
