# Generated by Django 5.1.4 on 2025-05-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_experience_company_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="start_date",
        ),
    ]
